
spring:
  application:
    name: app
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 225588
      url: jdbc:mysql://47.97.186.90:3306/memory?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useAffectedRows=true
  redis:
    database: 1
    host: 47.97.186.90
    port: 6379
    password: chenqiting
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
        max-wait: 1000
      shutdown-timeout: 100
  mail:
    host: smtp.qq.com
    port: 465
    username: 1179374184@qq.com
    password: kbtphmwneiyrhahj
    default-encoding: utf-8
    properties.mail.smtp.ssl.enable: true
    test-connection: true
#    properties:
#      smtp:
#        auth: true
#        starttls:
#          enable: true
#          required: true
#        socketFactory:
#          port: 465
#          class: javax.net.ssl.SSLSocketFactory
#          allback: false

mybatis:
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml


security:
  jwtDefaultExp: 1296000
server:
    port: 8002
